### ISSUE TITLE
chess.inCheckmate is not a function issue

### ISSUE THREAD

**Issue by Uli-7567** [jhlywa/chess.js#355]
Hi, I am making a react-three 3d chess game and when I move a piece I get the error.
Uncaught TypeError: chess.inCheckmate is not a function
    at GameScene.jsx:82:1
    at GameScene.jsx:108:1
    at moveToWrapper (Chessboard.jsx:45:1)
    at onClick (Chessboard.jsx:197:1)
    at onIntersect (index-6f0019d1.esm.js:833:1)
    at handleIntersects (index-6f0019d1.esm.js:698:1)
    at HTMLDivElement.handleEvent (index-6f0019d1.esm.js:844:1)

This is the code where the function is being implemented
might be an error on my side but I am not 100% sure.
`const updateBoard = useCallback((targetPosition, id) => {
        const chess = chessRef.current;
        setSelected([]);
        setPossibleMoves([]);

        setBoard((currentBoard) => {
            const newBoard = chess.board();

            newBoard.forEach((column, columnIndex) => {
                column.forEach((row, rowIndex) => {
                    if (row) {
                        if (
                            targetPosition[0] === columnIndex &&
                            targetPosition[1] === rowIndex
                        ) {
                            row.id = id;
                        } else {
                            row.id = currentBoard[columnIndex][rowIndex].id;
                        }
                    }
                });
            });

            return newBoard;
        });

        if ( chess.inCheckmate() || chess.isDraw() || chess.isStalemate() || chess.isThreefoldRepetition() || chess.isInsufficientMaterial() ) {
            setIsMatchOver(true);
        } else {
            setIsWhiteTurn((turn) => !turn);
        }
        },
        [setBoard]
    );`

**Comment by Uli-7567** [comment]
Just realized that is supposed to be isCheckmate and not inCheckmate. The documentation uses inCheckmate
